[tool.poetry]
name = "vivo-disk-download"
version = "0.1.0"
description = ""
authors = ["chentubai <chentubai@qq.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
httpx = "^0.28.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
